name: Django CI/CD

on:
  push:
    branches:
      - main
      - staging
      - dev
      
  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      # - name: Make migrations
      #   run:
      #     python3 manage.- name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      # - name: Make migrations
      #   run:
      #     python3 manage.py migrate

      # - name: Run server
      #   run:
      #     python3 manage.py runserver

      # - name: Run tests
      #   run:
      #     python manage.py test

      # - name: Install requirements
      #   run:
      #     pip install -r requirements.txt

      # - name: Check Syntax
      #   run:
      #     pre-commit run --all-filespy migrate

      # - name: Run server
      #   run:
      #     python3 manage.py runserver

      # - name: Run tests
      #   run:
      #     python manage.py test

      - name: Install requirements
        run:
          pip install -r requirements.txt

      - name: Check Syntax
        run:
          pre-commit run --all-files